### ISSUE TITLE
full circle

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-ml#9]
This Issue is an epic for the work on the concept of the full circle of scans and measurements for the Child Growth Monitor MVP.

Full circle means data flows 
1. from the App, 
2. to the Firebase Backend, 
3. into the measurement prediction service 
4. and the predictions back into the Firebase Backend 
5. and thus are displayed in the App in the Field.

- [x] Data from the Phone is uploaded to Cloud Firestore and Google Cloud Storage
- [ ] a trained model is being served on the internet
  - #8 Flask
  - Seldon
  - ML Kit for .tflite models https://firebase.google.com/docs/ml-kit/use-custom-models
  - GCP ML Engine https://console.cloud.google.com/mlengine
- [ ] do predictions and write back results
  - for Firebase ML Kit probably directly through the App?
  - for everything else a Firebase Function that gets invoked with every new measurements, takes the scan artefacts, calls the model server, writes back result to the scan measurement or creates a new scan measurement (the latter would need changes in the app to avoid an endless loop here)
td

**Comment by mmatiaschek** [comment]
i think Firebase ML Kit looks promising.
If that doesn't work, for example if we are using tensorflow operations that are not yet supported by tflite (but actually i don't think so), Firebase Functions to invoke a model server would be the next best thing.

If we are using #8 Flask server we would probably best run it on data.childgrowthmonitor.org with a let's encrypt enabled nginx or apache2 reverse proxy, but i don't know too much about Flask, maybe it also has Lets's encrypt capabilities that are easily enabled

**Comment by xMartin** [comment]
Another approach would be to make the model available to the app locally by either packaging it with the app (.apk) or implement our own way to sync it from a remote storage.

This has been done by others already and we'd avoid bandwidth issues and keep support for offline usage.

See https://github.com/Welthungerhilfe/cgm-scanner/issues/96
